maps/aim_osef_s.bsp
maps/aim_osef_s.txt
models/S3B/arc_fern.mdl
models/S3B/baril003.mdl
models/S3B/barrels_pallet.mdl
models/S3B/box_phone.mdl
models/S3B/bush16.mdl
models/S3B/buzzer_kt_gazel.mdl
models/S3B/buzzer_pa_car2.mdl
models/S3B/buzzer_teatp_toyota.mdl
models/S3B/doofbird.mdl
models/S3B/dumpster_lidclosed.mdl
models/S3B/elecswitch.mdl
models/S3B/grandjeep.mdl
models/S3B/pallet_with_bags.mdl
models/S3B/tree_gshaded.mdl
models/S3B/xen_car1_1.mdl
sound/S3B/chirp.wav
sprites/S3B/black_smoke3.spr
