maps/aim_deagle_fiesta.bsp
maps/aim_deagle_fiesta.txt
gfx/env/2sertBK.tga
gfx/env/2sertDN.tga
gfx/env/2sertFT.tga
gfx/env/2sertLF.tga
gfx/env/2sertRT.tga
gfx/env/2sertUP.tga
models/S3B/herbes2.mdl
models/S3B/wood_barrel1.mdl
sound/S3B/eau.wav
